[package]
publish = false
name = "main"
version = "0.1.0"  # should match current 'memchr_n' version
edition = "2021"

[workspace]

[dependencies]
anyhow = "1.0.100"
memchr_n = { git = "https://github.com/Dr-Emann/memchr_n.git", branch = "wide-scan-128" }

[dependencies.shared]
path = "../../shared"

[[bin]]
name = "main"
path = "main.rs"

[profile.release]
debug = true
codegen-units = 1
lto = "fat"
